name: Nest
# Actual name is Nest
author: toyblocks
version: ${project.version}
description: ${project.description}

main: jp.llv.nest.NestPluginImpl

commands:
  nest:
    description: execute nest command
    usage: /nest <command>